delete from conditions;
SELECT SETVAL((SELECT pg_get_serial_sequence('conditions', 'condition_id')), 1, false);

insert into conditions (condition_name) values ('Asplenia');
insert into conditions (condition_name) values ('Chronic Liver Disease');
insert into conditions (condition_name) values ('HIV <200cells/mm3');
insert into conditions (condition_name) values ('HIV >200cells/mm3');
insert into conditions (condition_name) values ('Heart Disease/Chronic Lung Disease');
insert into conditions (condition_name) values ('Chronic Alcoholism');
insert into conditions (condition_name) values ('Immunocompromised-excluding HIV');
insert into conditions (condition_name) values ('Kidney Failure/Renal Disease');
insert into conditions (condition_name) values ('Homosexual Men');
insert into conditions (condition_name) values ('Pregnancy');
insert into conditions (condition_name) values ('Smoker');
insert into conditions (condition_name) values ('Illicit Drug Abuse');
insert into conditions (condition_name) values ('Clotting Factor Diseases');
insert into conditions (condition_name) values ('Diabetes');

delete from vaccines;
SELECT SETVAL((SELECT pg_get_serial_sequence('vaccines', 'vaccine_id')), 1, false);
insert into vaccines (vaccine_name, min_age_months, max_age_months, vaccine_desc) values ('Hepatitis A','12',null,'Hepatitis A is a liver disease spread by contaminated food and water.  It can also be spread from the hands of a person with hepatitis A. It is rarely spread through sexual contact.');
insert into vaccines (vaccine_name, min_age_months, max_age_months, vaccine_desc) values ('Hepatitis B','0',null,'Hepatitis B is a contagious virus that is transmitted through blood, blood products, and other body fluids (such as semen). Travelers can become infected through unprotected sex with an infected person, injection drug use, and transfusions with unscreened blood.');
insert into vaccines (vaccine_name, min_age_months, max_age_months, vaccine_desc) values ('Herpes Zoster','720',null,'Shingles (herpes zoster) is a painful skin rash that develops on one side of the face or body. Shingles vaccine reduces the risk of developing shingles and the long-term pain that can follow. Your risk of shingles and long-term pain from the disease increases as you age.');
insert into vaccines (vaccine_name, min_age_months, max_age_months, vaccine_desc) values ('MMR','12',null,'Measles is the most deadly of all childhood rash/fever illnesses. The disease spreads very easily, so it is important to protect against infection. To prevent measles, children (and some adults) should be vaccinated with the measles, mumps, and rubella (MMR) vaccine. ');
insert into vaccines (vaccine_name, min_age_months, max_age_months, vaccine_desc) values ('Polio','2',null,'Polio is a disease caused by a virus that affects the nervous system and is mainly spread by person-to-person contact. Polio can also be spread by drinking water or other drinks or eating raw or undercooked food that are contaminated with the feces of an infected person.');

delete from countries;
SELECT SETVAL((SELECT pg_get_serial_sequence('countries', 'country_code')), 1, false);
insert into countries (country_code, country_name) values ('AF','Afghanistan');
insert into countries (country_code, country_name) values ('AL','Albania');
insert into countries (country_code, country_name) values ('DZ','Algeria');
insert into countries (country_code, country_name) values ('AS','American Samoa');
insert into countries (country_code, country_name) values ('AD','Andorra');
insert into countries (country_code, country_name) values ('AO','Angola');
insert into countries (country_code, country_name) values ('AI','Anguilla');
insert into countries (country_code, country_name) values ('AQ','Antarctica');
insert into countries (country_code, country_name) values ('AG','Antigua and Barbuda');
insert into countries (country_code, country_name) values ('AR','Argentina');
insert into countries (country_code, country_name) values ('AM','Armenia');
insert into countries (country_code, country_name) values ('AW','Aruba');
insert into countries (country_code, country_name) values ('AU','Australia');
insert into countries (country_code, country_name) values ('AT','Austria');
insert into countries (country_code, country_name) values ('AZ','Azerbaijan');
insert into countries (country_code, country_name) values ('BS','Bahamas');
insert into countries (country_code, country_name) values ('BH','Bahrain');
insert into countries (country_code, country_name) values ('BD','Bangladesh');
insert into countries (country_code, country_name) values ('BB','Barbados');
insert into countries (country_code, country_name) values ('BY','Belarus');
insert into countries (country_code, country_name) values ('BE','Belgium');
insert into countries (country_code, country_name) values ('BZ','Belize');
insert into countries (country_code, country_name) values ('BJ','Benin');
insert into countries (country_code, country_name) values ('BM','Bermuda');
insert into countries (country_code, country_name) values ('BT','Bhutan');
insert into countries (country_code, country_name) values ('BO','Bolivia');
insert into countries (country_code, country_name) values ('BA','Bosnia and Herzegovina');
insert into countries (country_code, country_name) values ('BW','Botswana');
insert into countries (country_code, country_name) values ('BR','Brazil');
insert into countries (country_code, country_name) values ('IO','British Indian Ocean Territory');
insert into countries (country_code, country_name) values ('VG','British Virgin Islands');
insert into countries (country_code, country_name) values ('BN','Brunei');
insert into countries (country_code, country_name) values ('BG','Bulgaria');
insert into countries (country_code, country_name) values ('BF','Burkina Faso');
insert into countries (country_code, country_name) values ('BI','Burundi');
insert into countries (country_code, country_name) values ('KH','Cambodia');
insert into countries (country_code, country_name) values ('CM','Cameroon');
insert into countries (country_code, country_name) values ('CA','Canada');
insert into countries (country_code, country_name) values ('CV','Cape Verde');
insert into countries (country_code, country_name) values ('KY','Cayman Islands');
insert into countries (country_code, country_name) values ('CF','Central African Republic');
insert into countries (country_code, country_name) values ('TD','Chad');
insert into countries (country_code, country_name) values ('CL','Chile');
insert into countries (country_code, country_name) values ('CN','China');
insert into countries (country_code, country_name) values ('CX','Christmas Island');
insert into countries (country_code, country_name) values ('CC','Cocos Islands');
insert into countries (country_code, country_name) values ('CO','Colombia');
insert into countries (country_code, country_name) values ('KM','Comoros');
insert into countries (country_code, country_name) values ('CK','Cook Islands');
insert into countries (country_code, country_name) values ('CR','Costa Rica');
insert into countries (country_code, country_name) values ('HR','Croatia');
insert into countries (country_code, country_name) values ('CU','Cuba');
insert into countries (country_code, country_name) values ('CW','Curacao');
insert into countries (country_code, country_name) values ('CY','Cyprus');
insert into countries (country_code, country_name) values ('CZ','Czech Republic');
insert into countries (country_code, country_name) values ('CD','Democratic Republic of the Congo');
insert into countries (country_code, country_name) values ('DK','Denmark');
insert into countries (country_code, country_name) values ('DJ','Djibouti');
insert into countries (country_code, country_name) values ('DM','Dominica');
insert into countries (country_code, country_name) values ('DO','Dominican Republic');
insert into countries (country_code, country_name) values ('TL','East Timor');
insert into countries (country_code, country_name) values ('EC','Ecuador');
insert into countries (country_code, country_name) values ('EG','Egypt');
insert into countries (country_code, country_name) values ('SV','El Salvador');
insert into countries (country_code, country_name) values ('GQ','Equatorial Guinea');
insert into countries (country_code, country_name) values ('ER','Eritrea');
insert into countries (country_code, country_name) values ('EE','Estonia');
insert into countries (country_code, country_name) values ('ET','Ethiopia');
insert into countries (country_code, country_name) values ('FK','Falkland Islands');
insert into countries (country_code, country_name) values ('FO','Faroe Islands');
insert into countries (country_code, country_name) values ('FJ','Fiji');
insert into countries (country_code, country_name) values ('FI','Finland');
insert into countries (country_code, country_name) values ('FR','France');
insert into countries (country_code, country_name) values ('PF','French Polynesia');
insert into countries (country_code, country_name) values ('GA','Gabon');
insert into countries (country_code, country_name) values ('GM','Gambia');
insert into countries (country_code, country_name) values ('GE','Georgia');
insert into countries (country_code, country_name) values ('DE','Germany');
insert into countries (country_code, country_name) values ('GH','Ghana');
insert into countries (country_code, country_name) values ('GI','Gibraltar');
insert into countries (country_code, country_name) values ('GR','Greece');
insert into countries (country_code, country_name) values ('GL','Greenland');
insert into countries (country_code, country_name) values ('GD','Grenada');
insert into countries (country_code, country_name) values ('GU','Guam');
insert into countries (country_code, country_name) values ('GT','Guatemala');
insert into countries (country_code, country_name) values ('GG','Guernsey');
insert into countries (country_code, country_name) values ('CN','Guinea');
insert into countries (country_code, country_name) values ('GW','Guinea-Bissau');
insert into countries (country_code, country_name) values ('GY','Guyana');
insert into countries (country_code, country_name) values ('HT','Haiti');
insert into countries (country_code, country_name) values ('HN','Honduras');
insert into countries (country_code, country_name) values ('HK','Hong Kong');
insert into countries (country_code, country_name) values ('HU','Hungary');
insert into countries (country_code, country_name) values ('IS','Iceland');
insert into countries (country_code, country_name) values ('IN','India');
insert into countries (country_code, country_name) values ('ID','Indonesia');
insert into countries (country_code, country_name) values ('IR','Iran');
insert into countries (country_code, country_name) values ('IQ','Iraq');
insert into countries (country_code, country_name) values ('IE','Ireland');
insert into countries (country_code, country_name) values ('IM','Isle of Man');
insert into countries (country_code, country_name) values ('IL','Isreal');
insert into countries (country_code, country_name) values ('IT','Italy');
insert into countries (country_code, country_name) values ('CI','Ivory Coast');
insert into countries (country_code, country_name) values ('JM','Jamaica');
insert into countries (country_code, country_name) values ('JP','Japan');
insert into countries (country_code, country_name) values ('JE','Jersey');
insert into countries (country_code, country_name) values ('JO','Jordan');
insert into countries (country_code, country_name) values ('KZ','Kazakhstan');
insert into countries (country_code, country_name) values ('KE','Kenya');
insert into countries (country_code, country_name) values ('KI','Kiribati');
insert into countries (country_code, country_name) values ('XK','Kosovo');
insert into countries (country_code, country_name) values ('KW','Kuwait');
insert into countries (country_code, country_name) values ('KG','Kyrgyzstan');
insert into countries (country_code, country_name) values ('LA','Laos');
insert into countries (country_code, country_name) values ('LV','Latvia');
insert into countries (country_code, country_name) values ('LB','Lebanon');
insert into countries (country_code, country_name) values ('LS','Lesotho');
insert into countries (country_code, country_name) values ('LR','Liberia');
insert into countries (country_code, country_name) values ('LY','Libya');
insert into countries (country_code, country_name) values ('LI','Liechtenstein');
insert into countries (country_code, country_name) values ('LT','Lithuania');
insert into countries (country_code, country_name) values ('LU','Luxembourg');
insert into countries (country_code, country_name) values ('MO','Macao');
insert into countries (country_code, country_name) values ('MK','Macedonia');
insert into countries (country_code, country_name) values ('MG','Madagascar');
insert into countries (country_code, country_name) values ('MW','Malawi');
insert into countries (country_code, country_name) values ('MY','Malaysia');
insert into countries (country_code, country_name) values ('MV','Maldives');
insert into countries (country_code, country_name) values ('ML','Mali');
insert into countries (country_code, country_name) values ('MT','Malta');
insert into countries (country_code, country_name) values ('MH','Marshall Islands');
insert into countries (country_code, country_name) values ('MR','Mauritania');
insert into countries (country_code, country_name) values ('MU','Mauritius');
insert into countries (country_code, country_name) values ('YT','Mayotte');
insert into countries (country_code, country_name) values ('MX','Mexico');
insert into countries (country_code, country_name) values ('FM','Micronesia');
insert into countries (country_code, country_name) values ('MD','Moldova');
insert into countries (country_code, country_name) values ('MC','Monaco');
insert into countries (country_code, country_name) values ('MN','Mongolia');
insert into countries (country_code, country_name) values ('ME','Montenegro');
insert into countries (country_code, country_name) values ('MS','Montserrat');
insert into countries (country_code, country_name) values ('MA','Morocco');
insert into countries (country_code, country_name) values ('MZ','Mozambique');
insert into countries (country_code, country_name) values ('MM','Myanmar');
insert into countries (country_code, country_name) values ('NA','Namibia');
insert into countries (country_code, country_name) values ('NR','Nauru');
insert into countries (country_code, country_name) values ('NP','Nepal');
insert into countries (country_code, country_name) values ('NL','Netherlands');
insert into countries (country_code, country_name) values ('AN','Netherlands Antilles');
insert into countries (country_code, country_name) values ('NC','New Caledonia');
insert into countries (country_code, country_name) values ('NZ','New Zealand');
insert into countries (country_code, country_name) values ('NI','Nicaragua');
insert into countries (country_code, country_name) values ('NE','Niger');
insert into countries (country_code, country_name) values ('NG','Nigeria');
insert into countries (country_code, country_name) values ('NU','Niue');
insert into countries (country_code, country_name) values ('KP','North Korea');
insert into countries (country_code, country_name) values ('MP','Northern Mariana Islands');
insert into countries (country_code, country_name) values ('NO','Norway');
insert into countries (country_code, country_name) values ('OM','Oman');
insert into countries (country_code, country_name) values ('PK','Pakistan');
insert into countries (country_code, country_name) values ('PW','Palau');
insert into countries (country_code, country_name) values ('PS','Palestine');
insert into countries (country_code, country_name) values ('PA','Panama');
insert into countries (country_code, country_name) values ('PG','Papua New Guinea');
insert into countries (country_code, country_name) values ('PY','Paraguay');
insert into countries (country_code, country_name) values ('PE','Peru');
insert into countries (country_code, country_name) values ('PH','Phillippines');
insert into countries (country_code, country_name) values ('PN','Pitcairn');
insert into countries (country_code, country_name) values ('PL','Poland');
insert into countries (country_code, country_name) values ('PT','Portugal');
insert into countries (country_code, country_name) values ('PR','Puerto Rico');
insert into countries (country_code, country_name) values ('QA','QATAR');
insert into countries (country_code, country_name) values ('CG','Republic of the Congo');
insert into countries (country_code, country_name) values ('RE','Reunion');
insert into countries (country_code, country_name) values ('RO','Romania');
insert into countries (country_code, country_name) values ('RU','Russia');
insert into countries (country_code, country_name) values ('RW','Rwanda');
insert into countries (country_code, country_name) values ('BL','Saint Barthelemy');
insert into countries (country_code, country_name) values ('SH','Saint Helena');
insert into countries (country_code, country_name) values ('KN','Saint Kitts and Nevis');
insert into countries (country_code, country_name) values ('LC','Saint Lucia');
insert into countries (country_code, country_name) values ('MF','Saint Martin');
insert into countries (country_code, country_name) values ('PM','Saint Pierre and Miquelon');
insert into countries (country_code, country_name) values ('VC','Saint Vincent and the Grenadines');
insert into countries (country_code, country_name) values ('WS','Samoa');
insert into countries (country_code, country_name) values ('SM','San Marino');
insert into countries (country_code, country_name) values ('ST','Sao Tome and Principe');
insert into countries (country_code, country_name) values ('SA','Saudi Arabia');
insert into countries (country_code, country_name) values ('SN','Senegal');
insert into countries (country_code, country_name) values ('RS','Serbia');
insert into countries (country_code, country_name) values ('SC','Seychelles');
insert into countries (country_code, country_name) values ('SL','Sierra Leone');
insert into countries (country_code, country_name) values ('SG','Singapore');
insert into countries (country_code, country_name) values ('SX','Sint Maarten');
insert into countries (country_code, country_name) values ('SK','Slovakia');
insert into countries (country_code, country_name) values ('SI','Slovenia');
insert into countries (country_code, country_name) values ('SB','Solomon Islands');
insert into countries (country_code, country_name) values ('SO','Somalia');
insert into countries (country_code, country_name) values ('ZA','South Africa');
insert into countries (country_code, country_name) values ('KR','South Korea');
insert into countries (country_code, country_name) values ('SS','South Sudan');
insert into countries (country_code, country_name) values ('ES','Spain');
insert into countries (country_code, country_name) values ('LK','Sri Lanka');
insert into countries (country_code, country_name) values ('SD','Sudan');
insert into countries (country_code, country_name) values ('SR','Suriname');
insert into countries (country_code, country_name) values ('SJ','Svalbard and Jan Mayen');
insert into countries (country_code, country_name) values ('SZ','Swaziland');
insert into countries (country_code, country_name) values ('SE','Sweden');
insert into countries (country_code, country_name) values ('CH','Switzerland');
insert into countries (country_code, country_name) values ('SY','Syria');
insert into countries (country_code, country_name) values ('TW','Taiwan');
insert into countries (country_code, country_name) values ('TJ','Tajikistan');
insert into countries (country_code, country_name) values ('TZ','Tanzania');
insert into countries (country_code, country_name) values ('TH','Thailand');
insert into countries (country_code, country_name) values ('TG','Togo');
insert into countries (country_code, country_name) values ('TK','Tokelau');
insert into countries (country_code, country_name) values ('TO','Tonga');
insert into countries (country_code, country_name) values ('TT','Trinidad and Tobago');
insert into countries (country_code, country_name) values ('TN','Tunisia');
insert into countries (country_code, country_name) values ('TR','Turkey');
insert into countries (country_code, country_name) values ('TM','Turkmenistan');
insert into countries (country_code, country_name) values ('TC','Turks and Caicos Islands');
insert into countries (country_code, country_name) values ('TV','Tuvalu');
insert into countries (country_code, country_name) values ('VI','U.S. Virgin Islands');
insert into countries (country_code, country_name) values ('UG','Uganda');
insert into countries (country_code, country_name) values ('UA','Ukraine');
insert into countries (country_code, country_name) values ('AE','United Arab Emirates');
insert into countries (country_code, country_name) values ('GB','United Kingdom');
insert into countries (country_code, country_name) values ('US','United States');
insert into countries (country_code, country_name) values ('UY','Uruguay');
insert into countries (country_code, country_name) values ('UZ','Uzbekistan');
insert into countries (country_code, country_name) values ('VU','Vanuatu');
insert into countries (country_code, country_name) values ('VA','Vatican');
insert into countries (country_code, country_name) values ('VE','Venezuela');
insert into countries (country_code, country_name) values ('VN','Vietnam');
insert into countries (country_code, country_name) values ('WF','Wallis and Futuna');
insert into countries (country_code, country_name) values ('EH','Western Sahara');
insert into countries (country_code, country_name) values ('YE','Yemen');
insert into countries (country_code, country_name) values ('ZM','Zambia');
insert into countries (country_code, country_name) values ('ZW','Zimbabwe');
